language: generic
services: docker
script: docker run -v ${TRAVIS_BUILD_DIR}:/travis -w /travis -it registry.gitlab.com/islandoftex/images/context:beta ./build.sh

before_deploy:
  - git config --local user.name "Travis CI"
  - git config --local user.email "https://travis-ci.org/"
  - git tag "`git show -s --no-show-signature --format=%ct HEAD`"

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: ./**/*.pdf
  skip_cleanup: true
  on:
    branch: master
    tags: false
